### ISSUE TITLE
task "Rename previous HE storage domain to avoid name conflicts" fails due to unknown variable

### ISSUE THREAD

**Issue by gematik-fue** [oVirt/ovirt-ansible-hosted-engine-setup#114]
The task "Rename previous HE storage domain to avoid name conflicts" fails with following error message

> The task includes an option with an undefined variable. The error was: 'STORAGE_DOMAIN_NAME' is undefined
> 
> The error appears to have been in '/usr/share/ansible/roles/ovirt.hosted_engine_setup/tasks/restore_backup.yml': line 71, column 3, but may
> be elsewhere in the file depending on the exact syntax problem.
> 
> The offending line appears to be:
> - debug: var=db_remove_he_host
> - name: Rename previous HE storage domain to avoid name conflicts
>   ^ here

OS: CentOS Linux release 7.6.1810 (Core)
version: ovirt-hosted-engine-setup-2.3.3-1.el7.noarch

I got around this issue by patching the file (but I'm not sure if this is the right way to fix it)
sed -i.bak 's/STORAGE_DOMAIN_NAME/he_storage_domain_name/' /usr/share/ansible/roles/ovirt.hosted_engine_setup/tasks/restore_backup.yml

https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/master/tasks/restore_backup.yml#L75-L76

**Comment by irosenzw** [comment]
fixed in #115
