### ISSUE TITLE
[DOCS] Add he_force_ip4 & he_force_ip6 to README

### ISSUE THREAD

**Issue by MosheSheena** [oVirt/ovirt-ansible-hosted-engine-setup#121]
Hi,
Can these params please be added to the README?
The code for these is already merged.

Thanks.

**Comment by sandrobonazzola** [comment]
@arachmani , @eslutsky can you please review?

**Comment by eslutsky** [comment]
is this the correct description?
```
he_force_ip4 - force resolving engine FQDN using the ipv4 DNS server.
he_force_ip6 -  force resolving engine FQDN using the ipv6 DNS server.
```

**Comment by MosheSheena** [comment]
@eslutsky, that sounds about right.
I understood these parameters best as -
"force resolving engine FQDN to IPv4 only" / "force resolving engine FQDN to IPv6 only"

Maybe we could also add a note saying using one of these two parameters, without having the DNS resolve the FQDN to the desired IP family will fail the deployment.

**Comment by arachmani** [comment]
Fixed in https://github.com/oVirt/ovirt-ansible-collection/pull/258
