### ISSUE TITLE
delegate_to won't resolve on remote host

### ISSUE THREAD

**Issue by callumstrubi** [oVirt/ovirt-ansible-hosted-engine-setup#151]
Currently the playbook is hanging on here when resolving the newly provisioned VM via the remote host:

```TASK [ovirt.hosted_engine_setup : Wait for the local VM]```

My understanding is that Ansible should use the details used as defined in the dynamically provisioned host entry for the VM, running the command as the remote_host as to benefit from the `/etc/hosts` routing but currently it won't, ping, despite a manual connection from hypervisor to VM working as expected.

**Comment by tiraboschi** [comment]
This works for me; are you deploying with IPv6 or IPv4?
DHCP or static?

**Comment by callumstrubi** [comment]
Static IPv4 only
# Network
he_vm_ip_addr: "10.141.31.240"
he_vm_ip_prefix: "20"
he_dns_addr: ["10.141.31.251","10.141.31.252","10.141.31.253"]
he_default_gateway_4: "10.141.31.254"
he_gateway: he_default_gateway_4
he_force_ip4: true
he_bridge_if: ovirtmgmt
he_just_collect_network_interfaces: true

**Comment by callumstrubi** [comment]
```<virthyp04.virt.in.bmrc.ox.ac.uk> ESTABLISH SSH CONNECTION FOR USER: None
<virthyp04.virt.in.bmrc.ox.ac.uk> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=g
ssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/etc/ansible/.ansible/cp/e6378a7fa7 virthyp04.virt.
in.bmrc.ox.ac.uk '/bin/sh -c '"'"'echo ~root && sleep 0'"'"''```
It seems that the user of "root" that is set against the dynamic ansible host is not being applied here. Unless you have a default ssh-connection user setup, this doesn't work. Though clearly the SSH extra opts are being set correctly, so this feels like a bug in ansible.
```ansible 2.8.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/etc/ansible/playbook/modules']
  ansible python module location = /opt/ansible/lib/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]```

**Comment by tiraboschi** [comment]
I think it's just a side effects of https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/issues/155
