### ISSUE TITLE
Ansible inventory for he_host has to be FQDN

### ISSUE THREAD

**Issue by callumstrubi** [oVirt/ovirt-ansible-hosted-engine-setup#156]
This probably just needs to be made clear at the readme level, but if the he_host is not fully qualified the task "Add an entry for this host on /etc/hosts on the local VM" will fail as it resolves `hostname[{{ he_host_fqdn }}]` or a variable to that affect, rather than referring to the actual inventory name defined.

**Comment by tiraboschi** [comment]
By default we use the result of $(hostname -f) but you can also pass a custom value for that using he_host_address; the same for the name (label) used at engine level (he_host_name).
It's already in README.md
