### ISSUE TITLE
in iscsi deployment we need to use only he_iscsi_portal_addr and not he_storage_domain_addr

### ISSUE THREAD

**Issue by kobihk** [oVirt/ovirt-ansible-hosted-engine-setup#158]
in iscsi deployment, we have 2 different variables that are the same:

- he_iscsi_portal_addr
- he_storage_domain_addr

I think that we need to use:

- he_storage_domain_addr in case of nfs and glusterfs deployment 
- he_iscsi_portal_addr in case of iscsi deployment

**Comment by tiraboschi** [comment]
he_iscsi_portal_addr appears just in tasks/iscsi_discover.yml and tasks/iscsi_getdevices.yml which are helpers tasks files for the the interactive iSCSI discovery via CLI and cockpit.
For the deployment only he_storage_domain_addr is relevant.
