### ISSUE TITLE
Please add to documentation the ovirt supported version

### ISSUE THREAD

**Issue by kobihk** [oVirt/ovirt-ansible-hosted-engine-setup#176]
AFAIU this role support only ovirt versions  >= 4.3
Could you please add it in the documentation to make it clear.

**Comment by sandrobonazzola** [comment]
@arachmani , @eslutsky can you please review?

**Comment by kobihk** [comment]
Since we moved to https://github.com/ovirt/ovirt-ansible-collection it is not needed
