### ISSUE TITLE
Failure while waiting for the host to be up

### ISSUE THREAD

**Issue by kostas-rs** [oVirt/ovirt-ansible-hosted-engine-setup#203]
Hello contributors, first of all i would like to thank you for you hard work providing these Ansible roles. 

To the issue at hand, i am trying to install oVirt engine in HA mode using this playbook.
Below are the variables i am using:

```
he_bridge_if: 'p3p1'
he_fqdn: 'engine.example.com'
he_vm_ip_addr: '192.168.44.189'
he_vm_ip_prefix: '24'
he_gateway: '192.168.44.254'
he_dns_addr:
  - '8.8.8.8'
  - '192.168.195.1'
  - '192.168.163.1'
he_vm_etc_hosts: true
he_vm_mac_addr: '00:a5:3f:66:ba:12'
he_domain_type: 'nfs'
he_storage_domain_path: "/var/nfs"
he_storage_domain_addr: 'nfs.example.com'
he_mem_size_MB: '8192'
he_vcpus: '2'
he_ansible_host_name: 'node-01.example.com'
he_host_name: 'node-01.example.com'
he_network_test: 'ping'
```

So currently i am running the playbook from my workstation PC targeting 'node-01.example.com'.

The role works fine until it reaches the point after it has added the host to the engine. Then it goes through the retries but it cannot get the right response back from the engine with the below ansible output:

```
TASK [ovirt.hosted_engine_setup : Wait for the host to be up] *******************************************************************************************************************************
task path: /Users/user/.ansible/roles/ovirt.hosted_engine_setup/tasks/bootstrap_local_vm/05_add_host.yml:111
fatal: [node-01.example.com]: FAILED! => {
    "ansible_facts": {
        "ovirt_hosts": []
    },
    "attempts": 120,
    "changed": false,
    "invocation": {
        "module_args": {
            "all_content": false,
            "fetch_nested": false,
            "nested_attributes": [],
            "pattern": "name={'changed': False, 'skipped': True, 'skip_reason': 'Conditional result was False'}"
        }
    }
}
```

Log from the ovirt-engine:

`2019-05-30 10:28:20,158+01 INFO  [org.ovirt.engine.core.bll.SearchQuery] (default task-1) [6f91508e-4f5e-4a5d-b3a1-23f96af7e24b] ResourceManager::searchBusinessObjects - erroneous search text - ''Hosts : name={'changed': False, 'skipped': True, 'skip_reason': 'Conditional result was False'}'' error - ''Hosts : name=$'c$hanged': False, 'skipped': True, 'skip_reason': 'Conditional result was False'}''`

I am running the following software:

- Ansible 2.7.8 on Mac OS
- Latest Ansible roles (downloaded from ansible-galaxy)
- oVirt node 4.4.0 for the host OS

Thank you

**Comment by tiraboschi** [comment]
Thanks for the report,
[here](https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/master/tasks/bootstrap_local_vm/05_add_host.yml#L113) we clearly have 
`pattern: name={{ he_host_name }}`
and in your variable file you have:
`he_host_name: 'node-01.example.com'`
so he_host_name got probably overwrote by the result of a previous failure.
Can you please checks you log for that or send them to me?

I'd suggest to re-execute with -vvv

**Comment by tiraboschi** [comment]
Just to make it more clear,
the issue is that the code passed:
`            "pattern": "name={'changed': False, 'skipped': True, 'skip_reason': 'Conditional result was False'}"`
instead of
`             "pattern": "name='node-01.example.com'"`
as expected

**Comment by tiraboschi** [comment]
Another thing, oVirt 4.3.z is the stable version, oVirt 4.4 is the development branch

**Comment by kostas-rs** [comment]
Hi @tiraboschi, thank you for your suggestions. I have located the issue, here is the Ansible log where the issue occurs:

```
2019-05-30 11:48:53,122 p=5769 u=user |  TASK [ovirt.hosted_engine_setup : Get full hostname] ****************************************************************************************************************************************
2019-05-30 11:48:53,123 p=5769 u=user |  task path: /Users/user/.ansible/roles/ovirt.hosted_engine_setup/tasks/fetch_host_ip.yml:2
2019-05-30 11:48:53,123 p=5769 u=user |  changed: [node-01.example.com] => {
    "changed": true,
    "cmd": [
        "hostname",
        "-f"
    ],
    "delta": "0:00:00.025521",
    "end": "2019-05-30 11:48:52.608310",
    "invocation": {
        "module_args": {
            "_raw_params": "hostname -f",
            "_uses_shell": false,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "warn": true
        }
    },
    "rc": 0,
    "start": "2019-05-30 11:48:52.582789",
    "stderr": "",
    "stderr_lines": [],
    "stdout": "node-01.example.com",
    "stdout_lines": [
        "node-01.example.com"
    ]
}
2019-05-30 11:48:53,227 p=5769 u=user |  TASK [ovirt.hosted_engine_setup : debug] ****************************************************************************************************************************************************
2019-05-30 11:48:53,227 p=5769 u=user |  task path: /Users/user/.ansible/roles/ovirt.hosted_engine_setup/tasks/fetch_host_ip.yml:11
2019-05-30 11:48:53,228 p=5769 u=user |  ok: [node-01.example.com] => {
    "he_host_name": {
        "changed": false,
        "skip_reason": "Conditional result was False",
        "skipped": true
    }
}
```

At this point the he_host_name variable is set to the skipped result coming from ansible. To quickly fix the issue i have commented our this line: https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/blob/38a3f86e65855df7ef0220ef28202fcfb9a80db6/tasks/fetch_host_ip.yml#L9 and then the play continues successfully.
