### ISSUE TITLE
it fails to install over a vlan tagged lacp bond

### ISSUE THREAD

**Issue by serverplumber** [oVirt/ovirt-ansible-hosted-engine-setup#249]
TASK [ovirt.hosted_engine_setup : Parse libvirt default network configuration] *********************************************************
fatal: [voyager]: FAILED! => {"changed": false, "msg": "network default not found"}

**Comment by tiraboschi** [comment]
Libvirt default network is used to temporary bootstrap the engine VM over a NAT network but it's not related to the device selected for the management bridge.
Can you please share the relevant logs?

**Comment by serverplumber** [comment]
I'm not sure what the installer is trying to do, so I don't know what are the relevant logs.

Attached is the output of the playbook -v

[hosted_engine_deploy_localhost.log](https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/files/3653313/hosted_engine_deploy_localhost.log)

**Comment by serverplumber** [comment]
the default libvirt network is absent.
I tried 
# net-define /usr/share/libvirt/networks/default.xml
then running your playbook again, no go.

**Comment by serverplumber** [comment]
Looks like the vm is trying to reach the network services from the libvirt default network. That's not going to work; it's going to get accesses denied all over the place. Can you list the resources it needs so we can allow it to reach them? perhaps make that part of the requirements?

**Comment by tiraboschi** [comment]
@serverplumber no external access is really required at setup time, if not we have a different issue.

**Comment by sandrobonazzola** [comment]
@arachmani , @eslutsky can you please review?

**Comment by eslutsky** [comment]
closing the issue, lack of information/logs.
