### ISSUE TITLE
installer fails with OVN configured host

### ISSUE THREAD

**Issue by sandersr** [oVirt/ovirt-ansible-hosted-engine-setup#250]
My host is configured with OVN and I wanted to re-deploy hosted engine. Currently this is not possible:

# ovs-vsctl show
f11dac71-55ba-4878-8a69-1296fade4f7d
    Bridge vdsmbr_htdZMRuz
        Port vdsmbr_htdZMRuz
            Interface vdsmbr_htdZMRuz
                type: internal
        Port ovirtmgmt
            tag: 3
            Interface ovirtmgmt
                type: internal
        Port "bond0"
            Interface "bond0"
        Port VMs
            tag: 5
            Interface VMs
                type: internal
    Bridge br-int
        fail_mode: secure
        Port "ovn-6e8d76-0"
            Interface "ovn-6e8d76-0"
                type: geneve
                options: {csum="true", key=flow, remote_ip="192.168.XX.XX"}
        Port br-int
            Interface br-int
                type: internal
        Port "ovn-f090b1-0"
            Interface "ovn-f090b1-0"
                type: geneve
                options: {csum="true", key=flow, remote_ip="192.168.XX.XX"}
    ovs_version: "2.11.0"

`[ INFO  ] TASK [ovirt.hosted_engine_setup : Detecting interface on existing management bridge]
[ ERROR ] fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'interfaces'\n\nThe error appears to be in '/usr/share/ansible/roles/ovirt.hosted_engine_setup/tasks/pre_checks/001_validate_network_interfaces.yml': line 4, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  block:\n  - name: Detecting interface on existing management bridge\n    ^ here\n"}
[ ERROR ] Failed to execute stage 'Environment customization': Failed executing ansible-playbook`

Please add OVN support.

**Comment by tiraboschi** [comment]
@sandersr can you please attach the output of `ansible -m setup localhost` executed on that host?

**Comment by sandersr** [comment]
Log attached:
[ansible_localhost.txt](https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/files/3674002/ansible_localhost.txt)

I understand that OVN is currently in Tech Preview on oVirt, but it works perfectly fine with hosted-engine running on it. Currently some manual magic is required but it would be nice to enable it as a deployment option.


ovs-vsctl show
a19b5587-688c-4ff2-b6e4-5bc66941155e
    Bridge br-int
        fail_mode: secure
        Port "patch-br-int-to-3d11b5a4-4d93-4d84-a37c-6bd0d3acc3c2"
            Interface "patch-br-int-to-3d11b5a4-4d93-4d84-a37c-6bd0d3acc3c2"
                type: patch
                options: {peer="patch-3d11b5a4-4d93-4d84-a37c-6bd0d3acc3c2-to-br-int"}
        Port "ovn-6e8d76-0"
            Interface "ovn-6e8d76-0"
                type: geneve
                options: {csum="true", key=flow, remote_ip="192.168.21.12"}
        Port "vnet0"
            Interface "vnet0"
        Port "ovn-bb7b14-0"
            Interface "ovn-bb7b14-0"
                type: geneve
                options: {csum="true", key=flow, remote_ip="192.168.21.11"}
        Port br-int
            Interface br-int
                type: internal
    Bridge "vdsmbr_np8R7LgR"
        Port ovirtmgmt
            tag: 3
            Interface ovirtmgmt
                type: internal
        Port VMs
            tag: 5
            Interface VMs
                type: internal
        Port "patch-3d11b5a4-4d93-4d84-a37c-6bd0d3acc3c2-to-br-int"
            Interface "patch-3d11b5a4-4d93-4d84-a37c-6bd0d3acc3c2-to-br-int"
                type: patch
                options: {peer="patch-br-int-to-3d11b5a4-4d93-4d84-a37c-6bd0d3acc3c2"}
        Port "vdsmbr_np8R7LgR"
            Interface "vdsmbr_np8R7LgR"
                type: internal
        Port "bond0"
            Interface "bond0"
    ovs_version: "2.11.0"

**Comment by sandrobonazzola** [comment]
@arachmani , @eslutsky can you please review?

**Comment by eslutsky** [comment]
OVS for management  Currently not supported on oVirt 4.4 hosts,
this is the bug  https://bugzilla.redhat.com/show_bug.cgi?id=1809102

OVN still can be used for  VM only internal networks.

**Comment by arachmani** [comment]
The bug mentioned in https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/issues/250#issuecomment-642613853 has been fixed, please try again using oVirt 4.4. 
In case you encounter the same problem again please open a bug in https://bugzilla.redhat.com/ or raise an issue in [ovirt-ansible-collection](https://github.com/oVirt/ovirt-ansible-collection)
