### ISSUE TITLE
Allow hosted-engine to be deployed on UEFI systems

### ISSUE THREAD

**Issue by sandersr** [oVirt/ovirt-ansible-hosted-engine-setup#252]
Currently hosted-engine-setup creates VM with he_emulated_machine: pc and standard BIOS. oVirt 4.3.0 added [Q35](https://bugzilla.redhat.com/1327846) support with UEFI.

Please consider adding Q35 chipset with UEFI setup for hosted-engine.

**Comment by sandrobonazzola** [comment]
Reported in bugzilla at https://bugzilla.redhat.com/show_bug.cgi?id=1757300 as RFE.
Closing here, it will be tracked there.
