### ISSUE TITLE
[RFE] Enable update of appliance from channels after VM is deployed

### ISSUE THREAD

**Issue by StLuke** [oVirt/ovirt-ansible-hosted-engine-setup#280]
It is common practice to consume old appliance and update packages from official repositories. However this we we might be unable to deploy the engine itself, as this is only possible after this role ends.

My suggestion is to have flag/variable controlling if `yum update` will run on the appliance VM right after it has been created and before engine-setup is run on it.

**Comment by tiraboschi** [comment]
The engine is deployed on the engine VM via [ovirt-ansible-engine-setup ansible role](https://github.com/oVirt/ovirt-ansible-engine-setup) which already has ovirt_engine_setup_update_all_packages option for this but in this role we are setting it to false to avoid failing on disconnected env.
We should eventually reconsider that.

**Comment by StLuke** [comment]
Keep the False as default, but open it to be changed by user?

**Comment by michalskrivanek** [comment]
I would argue to switch the default to True. Why would anyone want to work with outdated appliance? If it's disconnected, fine, it won't find any update, would it cause any harm?

**Comment by michalskrivanek** [comment]
what does need more thinking though, is the subscription for the HE VM in RHV use case. Any idea how to solve that?

**Comment by StLuke** [comment]
No internet connection to public channels?

**Comment by sandrobonazzola** [comment]
Tracking in bugzilla at https://bugzilla.redhat.com/show_bug.cgi?id=1816619

**Comment by sandrobonazzola** [comment]
Should be fixed via  oVirt/ovirt-ansible-engine-setup#77 and #313
