### ISSUE TITLE
ip -j rule -> Option "-j" is unknown on RHEL 7.8

### ISSUE THREAD

**Issue by jirimacku** [oVirt/ovirt-ansible-hosted-engine-setup#299]
The 01_prepare_routing_rules.yml fail because the ip command issued with unknown option

[root@lynx09 ~]# cat /etc/*elease
NAME="Red Hat Enterprise Linux"
VERSION="7.8"
VERSION_ID="7.8"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Red Hat Virtualization Host"
VARIANT_ID="ovirt-node"
PRETTY_NAME="Red Hat Virtualization Host 4.3.9 (el7.8)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.8:GA:hypervisor"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

# FIXME
REDHAT_BUGZILLA_PRODUCT="Red Hat Virtualization"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.8
REDHAT_SUPPORT_PRODUCT="Red Hat Virtualization"
REDHAT_SUPPORT_PRODUCT_VERSION=7.8
Red Hat Enterprise Linux release 7.8
Red Hat Enterprise Linux release 7.8

[root@lynx09 ~]# ip -j rule
Option "-j" is unknown, try "ip -help".

**Comment by tiraboschi** [comment]
We had a couple of changes ( #291 , #294 ) that are el8 specific and they are already contained in 1.0.36.
I'd suggest to create a release branch for el7 compatibility (1.0.z) and keep the el8 specific code only on 1.1.

**Comment by eslutsky** [comment]
@tiraboschi , we created branch `ovirt-4.3` for that purpose ,
all the el8 releases on master are versioned as 1.1.z .
@jirimacku , which version of ovirt-ansible-hosted-engine-setup are you using ?

**Comment by jirimacku** [comment]
@eslutsky normaly we use the master branch, now for the 4.3 we use the last good 1.0.x (1.0.35). I'll try the ovirt-4.3 branch and switch to that.
