### ISSUE TITLE
Support of hosted engine deploy from remote host

### ISSUE THREAD

**Issue by kobihk** [oVirt/ovirt-ansible-hosted-engine-setup#34]
Currently, we have the option to deploy only from localhost 
I would ask if you could add support to deploy the hosted engine from a remote host.

in our case, 
we want to deploy the hosted engine environment by using ansible from a remote machine.
the WA that we found for now is to run ansible-playbook as a shell from our ansible playbook like:
    - name: "Run HE ansible deploy locally on the first host"
      shell: "ansible-playbook /tmp/hosted_engine_deploy.yml --extra-vars='@/tmp/he_deployment.json'"

but IMHO 
1. It does not look good.
2. The task "stuck" for ~20 minutes without any output.
3. In the end, when the task is complete the output is hard to read.

**Comment by tiraboschi** [comment]
It should be addressed by this one: https://github.com/irosenzw/ovirt-ansible-hosted-engine-setup/pull/1/commits/9d66e31ef90c4f8caeb66182163438b8c73657ba
