### ISSUE TITLE
Task "Install oVirt Hosted Engine packages" still use yum module in Node 4.4.1.

### ISSUE THREAD

**Issue by fuchanghao** [oVirt/ovirt-ansible-hosted-engine-setup#356]
system: oVirt Node 4.4.1-2020071311   (https://resources.ovirt.org/pub/ovirt-4.4/iso/ovirt-node-ng-installer/4.4.1-2020071311/el8/)

When I tried to Migrate from a standalone Engine to a self-hosted engine.

After I do these command:

> hosted-engine --deploy --restore-from-file=file.backup

It tell me some error like this:

> [ INFO  ] TASK [ovirt.hosted_engine_setup : Install oVirt Hosted Engine packages]
> [ ERROR ] fatal: [localhost]: FAILED! => {"attempts": 10, "changed": false, "msg": "The Python 2 yum module is needed for this module. If you require Python 3 support use the `dnf` Ansible module instead."}
> [ ERROR ] Failed to execute stage 'Closing up': Failed executing ansible-playbook

I've already done "ovirt-hosted-engine-cleanup" before deploy.

Full SSH log:

[SSH log.txt](https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/files/4985595/SSH.log.txt)

Full error loge:

[ovirt-hosted-engine-setup-20200728095418-e64xay.log](https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/files/4985594/ovirt-hosted-engine-setup-20200728095418-e64xay.log)

**Comment by tvigers** [comment]
+1

Difference here is that I get this issue when trying to deploy on a fresh ovirt node.

**Comment by arachmani** [comment]
It seems like you hit https://bugzilla.redhat.com/show_bug.cgi?id=1858234
Please use the latest version of ovirt-node
