### ISSUE TITLE
Module copy issue introduced in ansible 2.9.12

### ISSUE THREAD

**Issue by mnecas** [oVirt/ovirt-ansible-hosted-engine-setup#363]
Hi,
there is an issue introduced in ansible 2.9.12.
The issue is when copying files the destination does not have the same permission as the original (it has 0600).
Please check your role for this issue.

**Comment by mnecas** [comment]
@arachmani @tiraboschi @sandrobonazzola 
cc @mwperina

**Comment by arachmani** [comment]
Thanks @mnecas, already fixed in #361

**Comment by mnecas** [comment]
Happy to hear that!
