### ISSUE TITLE
Need to handle the scenario of running this role on deployed environment 

### ISSUE THREAD

**Issue by kobihk** [oVirt/ovirt-ansible-hosted-engine-setup#37]
Need to handle the scenario of running this role on deployed environment 

IMHO we should skip with an error message something like:
"This environment already deployed, to be able to redeploy please run the command ovirt-hosted-engine-cleanup  command on the <host>"

In my case the environment destroyed partially and I got the following error:
TASK [oVirt.hosted-engine-setup : Fail if user chose more memory then the available memory] ************************************************************************************************************************************************
task path: /tmp/ovirt-ansible-hosted-engine-setup/tasks/pre_checks/validate_memory_size.yml:35
Wednesday 05 December 2018  15:34:57 +0200 (0:00:00.045)       0:02:42.445 ****
fatal: [automation-xxx.yyy.com]: FAILED! => {
    "changed": false,
    "msg": "Not enough memory: 12288MB, while only 9740MB are available on the host"
}

**Comment by sandrobonazzola** [comment]
@arachmani , @eslutsky can you please review?

**Comment by arachmani** [comment]
Closing it based on https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/pull/38#issuecomment-642522359

**Comment by arachmani** [comment]
Closing it based on https://github.com/oVirt/ovirt-ansible-hosted-engine-setup/pull/38#issuecomment-642522359
